### ISSUE TITLE
Support pipeline_stages

### ISSUE THREAD

**Issue by patsevanton** [patrickjahns/ansible-role-promtail#105]
Hello! 
I try use ansible-role-promtail for Docker Container Logging using Promtail

I try genarate config from https://gist.github.com/ruanbekker/c6fa9bc6882e6f324b4319c5e3622460
```
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: containers
  entry_parser: raw

  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log

  # --log-opt tag="{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
  pipeline_stages:

  - json:
      expressions:
        stream: stream
        attrs: attrs
        tag: attrs.tag

  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: "tag"

  - labels:
      tag:
      stream:
      image_name:
      container_name:
      image_id:
      container_id:
```

How configure pipeline_stages in this role?

**Comment by patrickjahns** [comment]
As per https://github.com/patrickjahns/ansible-role-promtail#role-variables -  `promtail_config_scrape_configs` exposes the full upstream configuration for writing scrape_configs including pipeline_stages ( https://grafana.com/docs/loki/latest/clients/promtail/configuration/#scrape_configs ).

**Comment by patsevanton** [comment]
Thanks.

```
    promtail_config_scrape_configs:
      - job_name: containers
        entry_parser: raw

        static_configs:
        - targets:
            - localhost
          labels:
            job: containerlogs
            __path__: /var/lib/docker/containers/*/*log

        pipeline_stages:

        - json:
            expressions:
              stream: stream
              attrs: attrs
              tag: attrs.tag

        - regex:
            expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
            source: "tag"

        - labels:
            tag:
            stream:
            image_name:
            container_name:
            image_id:
            container_id:
```
