### ISSUE TITLE
run_once causes failures when not all nodes in batch get promtail

### ISSUE THREAD

**Issue by viq** [patrickjahns/ansible-role-promtail#112]
According to https://docs.ansible.com/ansible/latest/user_guide/playbooks_strategies.html#running-on-a-single-machine-with-run-once `run_once` means the task runs only on first node in batch. This fails when this role is included using e.g.
```yaml
    - role: ansible-role-promtail
      tags: promtail
      when: promtail_enabled
```
when not all nodes have `promtail_enabled: True`.
