### ISSUE TITLE
running tasks on localhost requires sudo permissions

### ISSUE THREAD

**Issue by codezninja** [patrickjahns/ansible-role-promtail#155]
Hi,

New to ansible and was trying to use this role. When I set `promtail_version: latest` in my vars the  role errors out with the following.

![image](https://user-images.githubusercontent.com/4400773/216389201-b1d918e1-4b37-4599-931f-747a1d512b96.png)

Now in another run, I set `ANSIBLE_DEBUG=true` since it seemed like thats how I can enable `no_log=false` but I can't really make heads or tail what the error is in the very verbose output. 
But ff I set that var to a number it works fine since it uses another task step to download the binary.

So my question is, any guidance on how to debug this better so I can fix the problem?

**Comment by patrickjahns** [comment]
@codezninja  

From your description, the problem does not seem to be related directly to the role and more of an environment issue. 
Right now it's hard to provide any guidance - as a lot of information is missing. Especially having the  full text output of a run with `ANSIBLE_DEBUG=true`. 

If you are failing with setting `ANSIBLE_DEBUG=true` might I suggest that you just edit the role locally and set `no_log=false` manually on the task?

**Comment by codezninja** [comment]
I'll try and get some more debug information.

**Comment by codezninja** [comment]
This is the output from that task when `no_log=false` 
![image](https://user-images.githubusercontent.com/4400773/218379660-b7a57cb5-a00c-4310-a27c-a3a93e71c027.png)

**Comment by codezninja** [comment]
So it seems like the `delegate_to: localhost` was the issue that I was having when using version 1.21.0. When I comment that part out. It works as expected. I see that the latest version of the module, we removed that attribute. So I'll test out the latest version 1.22.0 and see how it functions.

**Comment by patrickjahns** [comment]
@codezninja 

This seems still to be more of an issue with your environment / playbook. The role will not per-default elevate the privileges for the preflight tasks - please see: https://github.com/patrickjahns/ansible-role-promtail/blob/master/tasks/main.yml#L1-L22

Please share your playbook and the way you are executing your playbook - the core cause for this is most likely there 

Can I also ask you, to share any issues as plaintext instead of screenshots. Screenshots are hard to read when it's text, as it is cropped to fit into size and makes it very uncomfortable to read. Thank you

**Comment by codezninja** [comment]
> Can I also ask you, to share any issues as plaintext instead of screenshots. Screenshots are hard to read when it's text, as it is cropped to fit into size and makes it very uncomfortable to read. Thank you

Sorry about that. Will do plaintext going forth.

> Please share your playbook and the way you are executing your playbook - the core cause for this is most likely there

So the playbook is pretty simple. I'm just running this with packer with the ansible provider. When the provider ssh into the system. It is as a `non-root user`, since root user ssh is locked down. I use ansible `become` to allow that user to become root before it executes the playbook. It's able to do that since that ssh user is allowed sudo privs

The problem I think is happening is that since part of the task in the role is delegated to `localhost`. Ansible is trying to run sudo on my local machine which it can't so it fails to run the task. [I opened a PR](https://github.com/patrickjahns/ansible-role-promtail/pull/160) that fixed my problem by not escalating the user for that task but I can just leave it in my fork if it's not what you desired.

`Playbook`
```yaml
---
- name: Setup promtail
  hosts: all
  become: true
  vars_files:
    - ./vars/default.yml
  roles:
    - { role: promtail,  tags: promtail }
```

`default.yml`
```
promtail_version: latest
promtail_log_level: debug
promtail_loki_server_url: https://my.domainname.com
promtail_config_scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      host: "{{ ansible_hostname }}"
      __path__: /var/log/*log
```
