### ISSUE TITLE
set acl for read rights

### ISSUE THREAD

**Issue by johanvdw** [patrickjahns/ansible-role-promtail#212]
This is a proposal. Using the code below it is possible to give the promtail user read access to /var/log regardless of the mode/owner. Is this something desirable for this role? Should it be configurable which paths get this access?

```
- name: Set ACL for promtail on /var/log
  acl:
    path: /var/log
    entity: promtail
    rights: rX
    recursive: yes
    state: present

```
